### ISSUE TITLE
Support for Oauth2 Authenciation

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/scicat-backend-next#107]
We need  to migrate OAuth2 authentication from the old backed into the new backend.

Some design notes:

We will need:
- A guard for OIDC - gets put in the decorator for the endpoint
- An OAuth strategy (extending the passport openid strategy)- tells you what to do with the result of Oauth, which you use to create the SciCat user profile.
- A mechanism to replace the profile loading callback from loopback3

The last point will require some investigation. How much do we want to support a generalized mechanism that replaces the login callback from the old backend and how much do we just rely on sites to implement their own code within the Auth strategy that they create (above)?

**Comment by minottic** [comment]
these could help:

1. in general: https://github.com/loopbackio/loopback-next/tree/master/examples/passport-login/src 
2. auth via oidc: https://github.com/paulscherrerinstitute/scilog/blob/psdk/sci-log-db/src/authentication-strategies/oidc.ts#L30-L33
3. user creation on the DB: https://github.com/loopbackio/loopback-next/blob/master/examples/passport-login/src/services/user.service.ts#L16-L95 (passed as the verify function to 2)
4.

**Comment by minottic** [comment]
@dylanmcreynolds , since we have some time to focus on this and we're thinking to use it soon, is it fine if I pick up this issue and implement?

**Comment by dylanmcreynolds** [comment]
@minottic sure, thanks! I've focused on the pyscicat stuff, so I would love if you did this.

**Comment by bolmsten** [comment]
Done? @dylanmcreynolds

**Comment by dylanmcreynolds** [comment]
> Done? @dylanmcreynolds

Yes, I have to figure out my strategy with multiple authenticators, but that could potentially be another PR.
