### ISSUE TITLE
GET /PublishedData/{id} is protected

### ISSUE THREAD

**Issue by minottic** [SciCatProject/scicat-backend-next#117]
## Issue Name

Comparing old be and new be, the GET /PublishedData/{id} has changed its permissions. Is there any reason for that? 

### Summary

GET /PublishedData/{id} now requires a valid access token

### Steps to Reproduce

GET /PublishedData/{id} without access token raises 401

### Current Behaviour

GET /PublishedData/{id} without access token raises 401

### Expected Behaviour

GET /PublishedData/{id} without access token should return the published data details (?)

**Comment by nitrosx** [comment]
Done with v4.2.1
