### ISSUE TITLE
Index on datasets collection causes issues

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/scicat-backend-next#121]
Techniques is a required field on Dataset. The Technique object is defined as: 

``` json
"techniques": [
    {
      "pid": "string",
      "name": "string"
    }
```
There is a unique index on `Datasets.techniques.pid`. Therefore, two datasets cannot share the same technique PID. Am I missing something here?

**Comment by stephan271** [comment]
Techniques should not be a required field, IMHO . However  I dont see why the index on Datasets.techniques.pid would require that pids can not be reused among datasets.

**Comment by nitrosx** [comment]
I agree with @stephan271.
IMHO, we should have an index on dataset's techniques, but it should not be unique.
The techniques field in dataset model should not be required.
