### ISSUE TITLE
OpenAPI doc does not speficy many data types

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/scicat-backend-next#122]
Take for example Datasets.

There are two similar but different model types in defined: `Dataset` and `CreateDatasetDto`. These are both used in the `POST` message to [/api/v3/datasets](http://localhost:3000/explorer-next/#/datasets/DatasetsController_create)

When you create a new dataset, you send `CreateDatasetDto` and receive a `Dataset` back in the response.

But then neither model is used again. The return types for getting datasets with fullQuery, and {id} or findOne simply return "object".

This presents a bit of a challenge for code generating libraries, which then give you typed objects.

**Comment by linupi** [comment]
There is a simmilar thing for the `CreateProposalDto` and `Proposal` model. 

I don't now much about openAPI but from what I see in Swagger the  `CreateProposalDto` schema (suppested by swagger for `POST /api/v3/proposals`) lists a lot of mandatory fields that are not mandatory at all to create a proposal while there is one that are currently causing  _internal server errors_ `MeasurementPeriodList` not beeing listed in the schema at all (https://github.com/SciCatProject/scicat-backend-next/issues/150#issuecomment-1246469410)

Similarly `POST /api/v3/datasets` expects  `creationLocation` and `principalInvestigator`, but they are not present in `CreateDatasetDto`. 

Maybe I just didn't understand so far what `CreateProposalDto` and `CreateDatasetDto` actually ment to be used for if is not to provide information of what is expected by te respective `POST` endpoints.

**Comment by nitrosx** [comment]
@linupi : I'm trying to make sure that data models and swagger openAPI definition are in sync. 
If you find any of those problems on branch SWAP-2755, please open an issue that I will fix while working on the tests

**Comment by nitrosx** [comment]
It is best practice to have a DTO for input and one for output, together with the database model which is only internal. 
In our case the output DTO matches the database model. 
This is the reason why for POST endpoint we have require the create DTO in input and we return the database model (aka output DTO) in output.

I'm closing this ticket. If need be, we can create more specific ones in the future.
