### ISSUE TITLE
GET datasets/{id} is protected even for published datasets

### ISSUE THREAD

**Issue by minottic** [SciCatProject/scicat-backend-next#124]
## Issue Name

GET datasets/{id} is protected even for published datasets

### Summary

In the old be GET datasets/{id} returned the dataset its property `isPublished=true`. The current implementation requires a valid auth token to get any dataset by {id}. Is there a reason for that? 

### Steps to Reproduce

GET datasets/{id} with an id of a published dataset returns 401

### Current Behaviour

GET datasets/{id} with an id of a published dataset returns 401

### Expected Behaviour

GET datasets/{id} with an id of a published dataset should return 200 and the dataset

**Comment by bolmsten** [comment]
fixed
