### ISSUE TITLE
Testing SWAP 2755 - no  request body for /api/v3/datasets in swagger

### ISSUE THREAD

**Issue by linupi** [SciCatProject/scicat-backend-next#152]
@nitrosx : As you suggested I use the SWAP-2755 for internal testing.

I saw that in the current version there is no _Request body_ for '/api/v3/datasets' in swagger anymore. Therefore one can no longer use swagger to push a new dataset. I guess this is some sort of open-api issue.

![Screenshot 2022-09-19 at 11-11-43 Swagger UI](https://user-images.githubusercontent.com/3169764/190986886-6149cf65-b484-43b5-ac6f-2483ac0512e2.png)

compared to _Sample_ where things are still ok:

![Screenshot 2022-09-19 at 11-11-15 Swagger UI](https://user-images.githubusercontent.com/3169764/190986893-a30505af-7b4b-4821-9679-cd228cf02275.png)

**Comment by linupi** [comment]
looking a bit into this again I saw that in the openAPI-json the 'requestBody' section is missing for the 'datasets' endpoint in the SWAP-2755 branch.

![grafik](https://user-images.githubusercontent.com/3169764/194009661-9f0af7ef-8107-4442-a0d6-4bdd8033b297.png)

compared to

![grafik](https://user-images.githubusercontent.com/3169764/194009737-1dc162ef-467f-4672-afec-311cc3445cf0.png)

**Comment by dylanmcreynolds** [comment]
This was reported (in less detail) in #122

**Comment by nitrosx** [comment]
Done and tested with v4.2.1
