### ISSUE TITLE
filters in fullquery don't work

### ISSUE THREAD

**Issue by linupi** [SciCatProject/scicat-backend-next#180]
While looking into #138 I saw that currently the filters in `api/v3/Datasets/fullquery` are not working at all. Giving a filter that **should not return any** datasets (at least it doesn't on the old backend) **now returns all** available datasets instead.

Here is an example filter on scientific metadata to reproduce this:

```
{"scientific":[{"lhs":"non_existing_key","relation":"EQUAL_TO_STRING","rhs":"non_existing_value"}]}
```

**Comment by nitrosx** [comment]
This case is now addressed by the backend and the full query now returns an empty array of datasets.
Will open a ticket to add specific tests.
