### ISSUE TITLE
Internal Server Error (400) when submitting payload

### ISSUE THREAD

**Issue by San-WierPa** [SciCatProject/scicat-backend-next#363]
### Summary

While using the scicat-backend image (I'm having a Déjà-vu)
+ I'm attempting to upload a JSON object to scicat, which is running in a docker-compose environment:
  `ghcr.io/scicatproject/backend-next:latest`
+ The application was functioning as expected until the pasted error started to occur during every dataset-upload attempt via the web interface and via local execution of a python-script
+ No changes were made to the application configuration or codebase prior to the error occurring.

Error:
```shell
{"detail": "Internal Server Error _(400)\nReason: Bad Request\nHTTP response headers: HTTPHeaderDict({'Access-Control-Allow-Origin': '*', 'Content-Length': '136', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Thu, 02 Mar 2023 22:22:26 GMT', 'Etag': 'W/\"88-CJlL1fjnC0I1fejwxIAAGCCJqLo\"', 'Set-Cookie': 'connect.sid=s%3A_X1GTa2ldGG8Z-ppf2CwWQ-6az5YKhFf.SAzez%2FtG8bzbbOhMXkubHpwBRx3JAxzrFGbCK%2BfBxwE; Path=/; HttpOnly', 'X-Powered-By': 'Express'})\nHTTP response body: {\"status\":400,\"message\":\"[{\\\"property\\\":\\\"ownerEmail\\\",\\\"children\\\":[],\\\"constraints\\\":{\\\"isEmail\\\":\\\"ownerEmail must be an email\\\"}}]\"}\n"}
```

### Current Behaviour

Upload of payload is stopped due to internal server error

### Expected Behaviour

Response 200

### Extra Details

I have had this error already countless times. Until now it disappeared "by itself" at some point (maybe because of an update of the scicat-backend?); however at the moment the error gets really into the way of successful developing.
I have tried using different images to resolve the error, but the issue persists.
I suspect the error may be caused by changes to the scicat codebase or dependencies, but cannot determine the exact cause.

Again, I have not done any changes on the payload. Can someone please help me identify the root cause of this error and provide a (long-term) solution?

Here is the payload (to clarify: I'm not touching the key "ownerEmail") :

```python
 {
            "owner_group": "University of Wuppertal",  #TODO
            "access_groups": "NO_THUMBNAIL", #TODO
            "creation_location": "wuppertal", #TODO
            "principal_investigator": "someone", #TODO
            "dataset_name": titlename
            + " "
            + datetime.now().strftime("%Y-%m-%d-%H_%M_%S"),
            "type": "raw", #TODO
            "is_published": False, #TODO
            "creation_time": str(datetime.now().isoformat()),
            "source_folder": "None",
            "owner": "None", #TODO
            "contact_email": "a@b.de", #TODO
            "scientific_metadata": {
                "Abstract": "This is a very descriptive and long informative abstract to understand this dataset a bit better!", #TODO
                "Source": "LABORATORY", #TODO
                "Mode": "ABSORPTION", #TODO
                "RAW": {
                    "edge_step": {
                        "value": 0.0,
                       
                        "documentation": "height of the detected edge step",
                    },
                    "k_max": {
                        "value": 0.0,
                        "unit": "1/angstrom",
                        "documentation": "considered angular wavenumber",
                    },
                    "noise": {
                        "value": 0.0,
                       
                        "documentation": "noise of the measurement",
                    },
                    "energy_resolution": {
                        "value": 0.0,
                        "unit": "eV",
                        "documentation": "energy resolution of the measured spectrum in eV",
                    },
                },
                "PROCESSED": {
                    "amplitude_reduction_factor": {
                        "Z_ranges": {
                            "tentoforty": {
                                "value": 0.0,
                            },
                            "fortytoeighty": {
                                "value": 0.0,
                            },
                        },
                        
                        "documentation": "amplitude factor from the processed spectrum",
                    }
                },
                "Figures": {
                    "data": None,
                    "k": None,
                    "R": None,
                },
            },
        }
```

**Comment by nitrosx** [comment]
@San-WierPa it looks like a validation error on ownerEmail.
Let me check and get back to you

**Comment by nitrosx** [comment]
I was able to replicate the issue via the swagger interface and the following payload:
```json 
{
 	"ownerGroup": "University of Wuppertal",
 	"accessGroups": "NO_THUMBNAIL",
 	"creationLocation": "wuppertal",
 	"principalInvestigator": "someone",
 	"datasetName": "Ingestion test for github ticket 363",
 	"type": "raw",
 	"isPublished": false,
 	"creationTime": "2023-03-02T08:00:00",
 	"sourceFolder": "None",
 	"owner": "Myself",
 	"contactEmail": "a@b.de",
 	"scientificMetadata": {
 		"Abstract": "This is a very descriptive and long informative abstract to understand this dataset a bit better!",
 		"Source": "LABORATORY",
 		"Mode": "ABSORPTION",
 		"RAW": {
 			"edge_step": {
 				"value": 0.0,
 				"documentation": "height of the detected edge step"
 			},
 			"k_max": {
 				"value": 0.0,
 				"unit": "1/angstrom",
 				"documentation": "considered angular wavenumber"
 			},
 			"noise": {
 				"value": 0.0,
 				"documentation": "noise of the measurement"
 			},
 			"energy_resolution": {
 				"value": 0.0,
 				"unit": "eV",
 				"documentation": "energy resolution of the measured spectrum in eV"
 			}
 		},
 		"PROCESSED": {
 			"amplitude_reduction_factor": {
 				"Z_ranges": {
 					"tentoforty": {
 						"value": 0.0
 					},
 					"fortytoeighty": {
 						"value": 0.0
 					}
 				},
 				"documentation": "amplitude factor from the processed spectrum"
 			}
 		},
 		"Figures": {
 			"data": "None",
 			"k": "None",
 			"R": "None"
 		}
 	}
 }
```

**Comment by nitrosx** [comment]
That's an expected behavior as ownerEmail fields should not exists.

**Comment by San-WierPa** [comment]
Thank you again for your fast response!

Two questions though:
1. Why does this error keep appearing/disappearing?
2. What am I missing? As far as I understand, my payload is not using any "ownerEmail" key. Is any key related to "email" a problem regarding that?

In conclusion; should I  avoid any such key for now?

Thank you in advance!

**Comment by pozsa** [comment]
Based on @martin-trajanovski's PR here's my theory of what's going on..

The error message you are getting looks to be inaccurate:
- it says `internal server error`. based on the error code and detailed information it should say that this is a client-side error.
- the detailed information looks to be inaccurate as well. the PR that was opened leads me to believe that currently `ownerEmail` is mandatory, and the error message should just tell you that it is missing/required.

**Comment by San-WierPa** [comment]
Hello and thank you for your response :)

That makes sense. It is probably known, that this error appears not with all versions right? Just now I've tried an older version, did not do any changes and it worked.

**Comment by nitrosx** [comment]
So, ownerEmail was indeed configured incorrectly in the Dataset dto. It was required and that's why you would get the error.
I just merged the PR and if you get the latest image it should be solved.
