### ISSUE TITLE
Incorrect type in schema for `dataFileList`

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/scicat-backend-next#450]
In the schemas for `OrigDatablock` and `Datablock`, the `dataFileList` has type `array[string]`. But in the DTOs (`CreateOrigDatablockDto`, `CreateDatasetOrigDatablockDto`, etc) it has type `array[DataFile]`.

It used to be `array[DataFile]` for all schemas / DTOs in the old backend. And as far as I can tell, it should be here as well.

**Comment by nitrosx** [comment]
Resolved with release v4.3.0
