### ISSUE TITLE
running migration scripts inside backend container does not work

### ISSUE THREAD

**Issue by linupi** [SciCatProject/scicat-backend-next#469]
https://github.com/SciCatProject/scicat-backend-next/blob/f2d689746d6a511ac77e42f1db16d265e555ac82/Dockerfile#L44-L46

We copy the migration scripts into the final docker image but when trying to run `npm run migrate:db:up` from inside the container (as stated in the documentation) it yields

```
~/app $ npm run migrate:db:up
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/node/app/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/node/app/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-04-26T06_54_55_860Z-debug-0.log
```

**Comment by bpedersen2** [comment]
I was able to run the migrations after adding:

 - package.json
 - scripts 
in the container 
and setting 
```export DB_MIGRATE_MONGODB_URL=$MONGODB_URI```
in the container shell
