### ISSUE TITLE
Intended usage of (orig)datablocks endpoints

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/scicat-backend-next#472]
There are multiple endpoints to access origdatablocks: `/datasets/<pid>/origdatablocks` and `/origdatablocks[/<pid>]`.
But for datablocks, there is only the former.

The models for `POST` differ slightly in that the latter endpoint requires `ownerGroup` and `datasetId`.

The latter works fine for uploading an origdatablock. But downloading does not seem to work, I'm getting an empty response.

Which one should be used?

**Comment by nitrosx** [comment]
`/datasets/<pid>/origdatablocks` was ported to v4.x for backward compatibility.
The preferred and supported way to interact with **origdatablocks** and **datablocks** is through their dedicated endpoints.

Please use `/origdatablocks[/<id>]` and `/datablocks[/<id>]`
Be aware that for this endpoints, <id> is the id of the [orig]datablock and not the pid of the dataset.

**Comment by nitrosx** [comment]
The POST model for `/origdatablock` requires the the `datasetId`, `ownerGroup` and `accessGroups`.
The POST model for `/dataset/<pid>/origdatablock` does not include such fields, as they are inferred from the dataset the origdatablock is associated with.

**Comment by nitrosx** [comment]
I tested and it works as it should at this moment.
If you have a dataset with `pid = 20.500.12269/556220d8-bb6c-41b4-9409-159b470539ec`, I can retrieve all the datasets with the call `datasets/20.500.12269%2F556220d8-bb6c-41b4-9409-159b470539ec/origdatablocks`.

Let's say that the first origdatablock has id `a2d40cbb-79a3-430a-8080-9ac47253a00f`, I can retrieve the origdatablocks with either the following two calls:
- `datasets/20.500.12269%2F556220d8-bb6c-41b4-9409-159b470539ec/origdatablocks` and than cycle through the array/list and extract the origdatablock with id `a2d40cbb-79a3-430a-8080-9ac47253a00f`
- `origdatablocks/a2d40cbb-79a3-430a-8080-9ac47253a00f`

That said, we encourage to use the `origdatablocks` endpoint to create and retrieve origdatablocks.

**Comment by nitrosx** [comment]
One last thing, to retrieve all origdatablocks associated with a specific dataset, we could use the `GET origdatablocks` endpoint with the appropriate filter.
I will create a ticket to update the documentation with some examples, also update the swagger interface.

Closing this issue, we can re-open it if needed.
