### ISSUE TITLE
Opinion - supertest vs pactum

### ISSUE THREAD

**Issue by nguyenlinhlinh** [SciCatProject/scicat-backend-next#70]
## Issue Name
Opinion on supertest vs pactum
### Summary
I tried out pactum while migrating test cases from the old backend to the new backend. I think the library is very good and also a lot easier to debug than supertest. One example could be when I want to see how the request I send to the backend looks like with supertest I need to console log and got a very huge object from supertest with all the things that might not related to the information I am looking for. With pactum I got the specific information I want to know. Looking at pactum's weekly download it doesn't have millions of downloads weekly like supertest but I think maybe it just because everyone is used to supertest. I create this issue to ask for opinion. If it is ok that I continue using pactum instead of supertest. If you know that supertest is better then let my know why since I haven't used supertest much and maybe the things I found inconvenient with supertest might be because I dont know the correct way to use it. @henrikjohansson712, @stephan271, @nitrosx, @minottic, @dylanmcreynolds.

**Comment by nitrosx** [comment]
@nguyenlinhlinh unfortunately, I do not have much experience with testing libraries in javascript. I would rely on your and the community expertise and experience to guide the decision.
That said, I'm not oppose to change testing library if you think the gain is worth it.

On this matter, I found this post where different testing libraries are compared: 
https://dev.to/asaianudeep/api-testing-tools-in-javascript-22d8

**Comment by henrikjohansson712** [comment]
I say we try it

**Comment by minottic** [comment]
I have no experience with pactum , but I am happy to give it a try

**Comment by nguyenlinhlinh** [comment]
Ok, Thank you. I will close this then :)
