### ISSUE TITLE
Versioning in the URL

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/scicat-backend-next#92]
At the last developers; meeting, we discussed the possibility of changing the version indicator in the enpoint urls from `v3` to `v4`. 

I have started playing with the new backend with an eye toward making pyscicat [compatible](https://github.com/SciCatProject/pyscicat/issues/18) with both the new and old by parsing the url provided to the client and changing the url that gets used for datasets based on the version that pyscicat is talking to. But I currently it's still using `v3`. If this is likely to change in the future, I'll continue down this path. If not, then I'll find another method to distinguish in pyscicat (probably with an optional parameter in the constructor.)

**Comment by stephan271** [comment]
I think we will always need the version numbers, in order to help with migration in case of imcompatible changes to the API. In my mind we should not drop it.

**Comment by dylanmcreynolds** [comment]
At the call this week, I mentioned that there were some possible alternatives to placing the version in the URL path that seem to be gaining traction. Here is a brief [summary](https://www.xmatters.com/blog/blog-four-rest-api-versioning-strategies/).

I do not have a super strong opinion here. The path is pretty explicit to developers, which is nice.

**Comment by stephan271** [comment]
Nice summary. Whatever we choose, we should have the version info "somewhere"

**Comment by dylanmcreynolds** [comment]
During the scicat meetings, it was decided:

Version number

- url will continue to have a v3 in it
- pyscicat will accept a setup parameter to say "new backend"
-
